# Generated by Django 5.0.7 on 2024-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_rename_number_person_person_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
