# Generated by Django 5.0.7 on 2024-07-31 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_alter_person_person_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='student',
            new_name='person',
        ),
    ]
