# Generated by Django 5.0.6 on 2024-08-03 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_student_field_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.field'),
        ),
    ]
