# Generated by Django 5.0.7 on 2024-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='gray_scale_image',
        ),
        migrations.AddField(
            model_name='images',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='origin_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
