# Generated by Django 5.0.7 on 2024-07-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_images_gray_scale_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
