# Generated by Django 5.0.7 on 2024-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.CharField(blank=True, choices=[(1, 'پردازش شده'), (0, 'پردازش نشده')], default=1, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='origin_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
