# Generated by Django 5.0.7 on 2024-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_message_alter_image_origin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='message',
            field=models.CharField(blank=True, choices=[(1, 'پردازش شده'), (0, 'پردازش نشده')], default='پردازش شده', max_length=30, null=True),
        ),
    ]
