# Generated by Django 5.0.7 on 2024-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_id',
            field=models.IntegerField(),
        ),
    ]
